#!/usr/bin/env python3
import sys


def solve(A: "List[int]", B: "List[int]"):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = [int(next(tokens)) for _ in range(9)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(8)]  # type: "List[int]"
    solve(A, B)

if __name__ == '__main__':
    main()
