#!/usr/bin/env python3
import sys
input = sys.stdin.readline

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = list(map(int, input().split()))
    inputs = [list(input().split()) for _ in range(N)]
    C = [int(inputs[i][0]) for i in range(N)]
    P = [int(inputs[i][1]) for i in range(N)]
    roulettes = [list(map(int, inputs[i][2:])) for i in range(N)]
    inf = 1e12  # B(10^4) * M(10^2)　より大きい
    dp = [inf] * (M + 1)
    dp[0] = 0.0
    for i in range(1, M + 1):
        for j in range(0, N):
            sum = 0.0
            zeros = roulettes[j].count(0)
            P_dash = P[j] - zeros
            for k in range(0, P[j]):
                if roulettes[j][k] == 0:
                 continue
                points = roulettes[j][k]
                prev = dp[i - points] if i - points > 0 else 0.0
                C_dash = C[j] * (P[j] / P_dash)
                sum += (prev + C_dash) / P_dash
            dp[i] = min(dp[i], sum)
    print(f'{dp[M]:.10f}')


if __name__ == '__main__':
    main()
