#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    [N, M] = list(map(int, (input().split())))
    A = list(map(int, (input().split())))
    B = list(map(int, (input().split())))
    i = 0
    j = 0
    ansA = [0] * N
    ansB = [0] * M
    while i < N or j < M:
        if j == M or (j < M and i < N and A[i] < B[j]):
            ansA[i] = i + j + 1
            i += 1
        else:
            ansB[j] = i + j + 1
            j += 1
    print(*ansA)
    print(*ansB)

if __name__ == '__main__':
    main()
