#!/usr/bin/env python3
import sys
from math import log2, ceil
input = sys.stdin.readline


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())
    pow = [-1] * 61
    pow[0] = 1
    for i in range(1, 61):
        pow[i] = pow[i - 1] * 2

    for _ in range(T):
        N, X, K = map(int, input().split())

        def cnt(rt: int, k: int, i: int) -> int:
            if i + k > 60:
                return 0

            if k < 0:
                return 0

            l = rt * pow[k]
            r = rt * pow[k] + pow[k] - 1
            # print(f'rt: {rt}, k: {k}, i:{i}, l:{l}, r:{r}', file=sys.stderr)
            return min(N, r) - l + 1 if l <= N else 0

        i = ceil(log2(X))
        ans = cnt(X, K, i)
        v = X
        par = v // 2
        sib = v ^ 1
        k = K - 1
        i -= 1
        while k >= 0 and v > 1:
            # print(f'v:{v} par:{par}, sib:{sib}, i:{i}', file=sys.stderr)

            if k == 0:
                ans += 1
            else:
                ans += cnt(sib, k - 1, i)

            v = par
            par = v // 2
            sib = v ^ 1
            i -= 1
            k -= 1

        print(ans)


if __name__ == '__main__':
    main()
