#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str

# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = list(map(int, input().split(' ')))
    S = input()
    T = input()

    dp = [[False] * (M + 1) for _ in range(N + 1)]
    dp[0][0] = True

    for i in range(N):
        for j in range(M):
            if not dp[i][j]:
                continue
            if S[i] == T[j]:   # Tの文字が続くケース
                dp[i + 1][j + 1] = True
            if S[i] == T[0]:    # どこからでもTの最初に戻ることができる
                dp[i + 1][1] = True

        # １個前にTが完成している場合は、好きな箇所に移動することができる
        if dp[i][M]:
            for j in range(M):
                if S[i] == T[j]:
                    dp[i + 1][j + 1] = True

        # print(f'dp[i + 1]={dp[i + 1]}', file=sys.stderr)

    if dp[N][M]:    # 最後はTが完成していないといけない
        print("Yes")
    else:
        print("No")


if __name__ == '__main__':
    main()
