#!/usr/bin/env python3
import sys


def solve(X_A: int, Y_A: int, X_B: int, Y_B: int, X_C: int, Y_C: int):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X_A = int(next(tokens))  # type: int
    Y_A = int(next(tokens))  # type: int
    X_B = int(next(tokens))  # type: int
    Y_B = int(next(tokens))  # type: int
    X_C = int(next(tokens))  # type: int
    Y_C = int(next(tokens))  # type: int
    solve(X_A, Y_A, X_B, Y_B, X_C, Y_C)

if __name__ == '__main__':
    main()
