#!/usr/bin/env python3
import sys


def solve(A: int, B: int, cnt: int):
#    print(A, B1, file=sys.stderr)
    if A < B:
        return solve(B, A, cnt)

    if A == B:
        print(cnt)
        return

    c = A // B
    if A % B == 0:
        return print(cnt + c - 1)

    return solve(B, A - c * B, cnt + c)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B, 0)

if __name__ == '__main__':
    main()
