#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int, i: int, j: int, k: int, l: int):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    c = int(next(tokens))  # type: int
    d = int(next(tokens))  # type: int
    e = int(next(tokens))  # type: int
    f = int(next(tokens))  # type: int
    g = int(next(tokens))  # type: int
    h = int(next(tokens))  # type: int
    i = int(next(tokens))  # type: int
    j = int(next(tokens))  # type: int
    k = int(next(tokens))  # type: int
    l = int(next(tokens))  # type: int
    solve(a, b, c, d, e, f, g, h, i, j, k, l)

if __name__ == '__main__':
    main()
