#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(x_A: int, y_A: int, x_B: int, y_B: int, x_C: int, y_C: int):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x_A = int(next(tokens))  # type: int
    y_A = int(next(tokens))  # type: int
    x_B = int(next(tokens))  # type: int
    y_B = int(next(tokens))  # type: int
    x_C = int(next(tokens))  # type: int
    y_C = int(next(tokens))  # type: int
    solve(x_A, y_A, x_B, y_B, x_C, y_C)

if __name__ == '__main__':
    main()
