#!/usr/bin/env python3
import sys
from atcoder.modint import Modint, ModContext
input = sys.stdin.readline
MOD = 998244353  # type: int


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    with ModContext(MOD):
        Q, K = map(int, input().split())
        dp = [Modint(0) for _ in range(K + 1)]
        dp[0] += 1
        # print(list(map(lambda x: x.val(), dp)), file=sys.stderr)
        for q in range(Q):
            sign, x = input().split()
            x = int(x)
            if sign == '+':
                for k in range(K, x - 1, -1):
                    dp[k] += dp[k - x]
            else:
                for k in range(x, K + 1):
                    dp[k] -= dp[k - x]

            # print(list(map(lambda x: x.val(), dp)), file=sys.stderr)
            print(dp[K].val())


if __name__ == '__main__':
    main()
