#!/usr/bin/env python3
import sys


def solve(N: int, M: int, U: "List[int]", V: "List[int]", W: "List[int]", Q: int, A: "List[int]", S: "List[int]", T: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    U = [int()] * (M)  # type: "List[int]"
    V = [int()] * (M)  # type: "List[int]"
    W = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
        W[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    A = [int()] * (Q)  # type: "List[int]"
    S = [int()] * (Q)  # type: "List[int]"
    T = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        A[i] = int(next(tokens))
        S[i] = int(next(tokens))
        T[i] = int(next(tokens))
    solve(N, M, U, V, W, Q, A, S, T)

if __name__ == '__main__':
    main()
