#!/usr/bin/env python3
# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
import sys
from atcoder.dsu import DSU

def main():
    N, Q = map(int, input().split())
    group_dsu = DSU(N + Q)  # group dsu
    ball_to_group = [i for i in range(N + Q)]   # ball to group
    to_box = [i for i in range(N + Q)]          # group to box
    to_group = [i for i in range(N + Q)]            # box to group
    cnt_group = N
    cnt_ball = N

    # i, jはgroup番号, toはbox
    def merge(gi: int, gj: int, to):
        par = group_dsu.merge(gi, gj)
        # print(f"bi:{bi} bj:{bj} par:{par}", file=sys.stderr)
        to_group[to] = par
        to_box[par] = to

    for _ in range(Q):
        query = list(map(int, input().split()))
        if query[0] == 1:
            box_x, box_y = query[1:]
            box_x -= 1
            box_y -= 1
            g_x, g_y = to_group[box_x], to_group[box_y]
            merge(g_x, g_y, box_x)

            # yに新しいグループを割り当てる
            to_group[box_y] = cnt_group
            to_box[cnt_group] = box_y

            cnt_group += 1

        elif query[0] == 2:
            box = query[1] - 1

            # ballをcnt_groupに属させる
            ball_to_group[cnt_ball] = cnt_group

            # いったん#cnt_groupのバーチャルboxに入れる
            to_box[cnt_group] = cnt_group
            to_group[cnt_group] = cnt_group

            merge(to_group[box], cnt_group, box)
            cnt_group += 1
            cnt_ball += 1
        else:
            ball = query[1] - 1
            box = to_box[group_dsu.leader(ball_to_group[ball])]
            print(box + 1)

        # print(f"ball_to_group:{ball_to_group} to_box:{to_box} to_group:{to_group}", file=sys.stderr)


if __name__ == '__main__':
    main()
