#!/usr/bin/env python3
import sys


def solve(R: int, G: int, B: int, C: str):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    G = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = next(tokens)  # type: str
    solve(R, G, B, C)

if __name__ == '__main__':
    main()
