#!/usr/bin/env python3

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    [L, N1, N2] = list(map(int, input().split()))
    def read():
        return list(map(int, input().split()))

    E1 = [read() for _ in range(N1)]
    E2 = [read() for _ in range(N2)]
    ans = 0

    i = 0
    j = 0
    e1 = [0, 0]
    e2 = [0, 0]
    while i < N1 or e1[1] > 0:
        if e1[1] == 0:
            e1 = E1[i]
            i += 1
        if e2[1] == 0:
            e2 = E2[j]
            j += 1
        len = min(e1[1], e2[1])
        e1[1] -= len
        e2[1] -= len
        if e1[0] == e2[0]:
            ans += len

    print(ans)
    pass

if __name__ == '__main__':
    main()
