#!/usr/bin/env python3
import sys


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = list(map(int, input().split(" ")))
    P = [list(map(lambda x: 1 if x == "B" else 0, input())) for _ in range(N)]
    queries = [list(map(int, input().split())) for _ in range(Q)]
    
    for i in range(N):
        for j in range(N - 1):
            P[i][j + 1] += P[i][j]

    for j in range(N):
        for i in range(N - 1):
            P[i + 1][j] += P[i][j]

    P = [[0] + P[i] for i in range(N)]
    P = [[0] * (N + 1)] + P

    # print(f'P={P}', file=sys.stderr)

    #  0-indexed
    def count_b(i, j):
        iq = i // N
        ir = i % N
        jq = j // N
        jr = j % N
        return iq * jq * P[N][N] + iq * P[N][jr] + jq * P[ir][N] + P[ir][jr]

    for i in range(Q):
        A, B, C, D = queries[i]
        ans = count_b(C + 1, D + 1) - count_b(A, D + 1) - count_b(C + 1, B) + count_b(A, B)
        print(ans)


if __name__ == '__main__':
    main()
