#!/usr/bin/env python3
import sys


def solve(N: int, M: int, L: int, a: "List[int]", b: "List[int]", c: "List[int]", d: "List[int]"):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    b = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    c = [int()] * (L)  # type: "List[int]"
    d = [int()] * (L)  # type: "List[int]"
    for i in range(L):
        c[i] = int(next(tokens))
        d[i] = int(next(tokens))
    solve(N, M, L, a, b, c, d)

if __name__ == '__main__':
    main()
