#!/usr/bin/env python3
import sys


def solve(N: int, D: "List[int]", L: "List[int]", C: "List[int]", K: "List[int]"):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    L = [int()] * (2)  # type: "List[int]"
    C = [int()] * (2)  # type: "List[int]"
    K = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        L[i] = int(next(tokens))
        C[i] = int(next(tokens))
        K[i] = int(next(tokens))
    solve(N, D, L, C, K)

if __name__ == '__main__':
    main()
