#!/usr/bin/env python3
import sys


def solve(H: int, W: int, K: int, S_i: int, S_j: int, A: "List[List[int]]"):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S_i = int(next(tokens))  # type: int
    S_j = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(W)] for _ in range(H)]  # type: "List[List[int]]"
    solve(H, W, K, S_i, S_j, A)

if __name__ == '__main__':
    main()
