#!/usr/bin/env python3
import sys


def solve(N: int, D: int, T: "List[int]"):
    for i in range(1, N):
        if T[i] - T[i - 1] <= D:
            print(T[i])
            return
    print(-1)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    T = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, D, T)

if __name__ == '__main__':
    main()
