#!/usr/bin/env python3
import sys


def solve(S: str, Q: int, T: "List[str]"):
    return


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    Q = int(next(tokens))  # type: int
    T = [next(tokens) for _ in range(Q)]  # type: "List[str]"
    solve(S, Q, T)

if __name__ == '__main__':
    main()
